#! /usr/bin/env php

<?php

use Acme\SayHelloCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Hello World Demo');

$app->add(new SayHelloCommand());

$app->run();
